#!/usr/bin/env bash

#
# bldr
#
# Performs the build process of an application
# in an ad-hoc container-like environment
#
#
# Author: André König <andre.koenig@posteo.de>
#

PKG=package.json
CWD=$(readlink -f .)
MANIFEST=$CWD/$PKG

figlet 'bldr'

if [ ! -f $MANIFEST ]; then
    echo "Well, there is no '$PKG' in this project. Exiting. Bye bye.
    "
    exit 1
fi

function getBuildCommand () {
    echo $(cat package.json | grep -Po '"build":.*?[^\\]",' | sed -e 's/\"build"\://g' | sed -e 's/\"//g' | sed -e 's/\,//g')
}

CMD=$(getBuildCommand)

if [ -z "$CMD" ]; then
    echo "No build command defined in the '$PKG'. Bye bye.
    "
    exit 1;
fi

schroot -c bldr -u $USER -- $CMD

exit 0
