#!/usr/bin/env bash

#
# bldr
#
# Performs the build process of an application
# in an ad-hoc container-like environment
#
#
# Author: André König <andre.koenig@posteo.de>
#

PKG=package.json
MANIFEST=$(pwd)/$PKG

if [ ! -f $MANIFEST ]; then
    echo "No '$PKG' found in this project. Bye bye."
fi

function getBuildCommand () {
    echo $(cat package.json | grep -Po '"build":.*?[^\\]",' | sed -e 's/\"build"\://g' | sed -e 's/\"//g' | sed -e 's/\,//g')
}

CMD=$(getBuildCommand)

if [ -z "$CMD" ]; then
    echo "No build command defined in the '$PKG'. Bye bye."
fi

schroot -c bldr -- $CMD
